import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { icons } from "lucide";

const outputUrl = new URL("../src/icons.ts", import.meta.url);
const checkOnly = process.argv.includes("--check");
const iconNames = Object.keys(icons).sort(compareAscii);

for (const name of iconNames) {
  if (!/^[$A-Z_a-z][$\w]*$/u.test(name)) {
    throw new Error(`Lucide exported an icon with an unsupported TypeScript name: ${name}`);
  }
}

const source = `${[
  "// This file is generated by scripts/generate-icons.mjs.",
  "// Run `npm run generate:icons` after updating Lucide. Do not edit this file by hand.",
  "",
  "import {",
  ...iconNames.map((name) => `  ${name} as ${name}Node,`),
  '} from "lucide";',
  'import { defineIcon } from "./index";',
  "",
  ...iconNames.map((name) => `export const ${name} = /* @__PURE__ */ defineIcon(${name}Node);`),
  "",
].join("\n")}`;

if (checkOnly) {
  const currentSource = await readFile(outputUrl, "utf8").catch(() => undefined);

  if (currentSource !== source) {
    console.error(
      `${fileURLToPath(outputUrl)} is out of date. Run \`npm run generate:icons\` and commit the result.`,
    );
    process.exitCode = 1;
  } else {
    console.log(`Generated icon module is up to date (${iconNames.length} exports).`);
  }
} else {
  await writeFile(outputUrl, source, "utf8");
  console.log(`Generated ${iconNames.length} Foldkit icon exports in ${fileURLToPath(outputUrl)}.`);
}

function compareAscii(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}
